repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  javax_inject: javax.inject:javax.inject:jar:1
  gwt_user: com.google.gwt:gwt-user:jar:2.5.1
  gwt_gin: com.google.gwt.inject:gin:jar:2.0.0
